### ISSUE TITLE
Working, or not?

### ISSUE THREAD

**Issue by ExTechOp** [otsaloma/helsinki-transit-live#5]
I don't think this is currently working, I get a map but no vehicles on it? About a month back the API once again seems to have changed and for example [JollaOpas](https://github.com/hsarkanen/JollaOpas) stopped working (I'm using JollaC with 2.2.0.29, in case it makes a difference).

**Comment by otsaloma** [comment]
The API is unstable indeed, either changed or broken. I haven't bothered to update Helsinki Transit Live as this kind of instability seems frequent and there is no news or proper documentation. Also, the introduction of real time stop schedules has made this app less relevant. So, I might or might not update it at some point, don't know if or when.

**Comment by otsaloma** [comment]
Now that I checked the details, it seems API has been undergone some changes, which look like it's either ready for production use or at least getting closer. So, I'll check if it works after adapting the code to the API changes. But, the plan is still to eventually move this to Pan Transit, I'll make minimal changes only.

https://digitransit.fi/en/developers/apis/4-realtime-api/vehicle-positions/

**Comment by otsaloma** [comment]
It does work, at least for now, I'll make a new release.

**Comment by ExTechOp** [comment]
Thanks, it indeed does work again! Now just wishing @hsarkanen got [JollaOpas](https://github.com/hsarkanen/JollaOpas/issues/15) fixed in a similar way.
